from pathlib import Path
main_py = '''import os import sqlite3 import logging from datetime import datetime, date from typing import Optional
from fastapi import FastAPI from aiogram import Bot, Dispatcher, F from aiogram.client.default import DefaultBotProperties from aiogram.enums import ParseMode from aiogram.filters import Command, CommandStart from aiogram.types import ( Message, CallbackQuery, InlineKeyboardMarkup, InlineKeyboardButton ) from aiogram.utils.keyboard import InlineKeyboardBuilder
logging.basicConfig(level=logging.INFO) log = logging.getLogger("viewcoin")
BOT_TOKEN = os.getenv("BOT_TOKEN", "").strip() if not BOT_TOKEN: raise RuntimeError("BOT_TOKEN environment variable is missing")
ADMIN_ID = int(os.getenv("ADMIN_ID", "5412332176")) WEBHOOK_URL = os.getenv("WEBHOOK_URL", "").rstrip("/") PORT = int(os.getenv("PORT", "10000")) DB_NAME = os.getenv("DB_NAME", "viewcoin.db") BOT_USERNAME = os.getenv("BOT_USERNAME", "ViewCoin_me_bot").lstrip("@") VIEW_CHANNEL = os.getenv("VIEW_CHANNEL", "@view_sin_channel") MEMBER_CHANNEL = os.getenv("MEMBER_CHANNEL", "@my_member_man")
bot = Bot(BOT_TOKEN, default=DefaultBotProperties(parse_mode=ParseMode.HTML)) dp = Dispatcher() app = FastAPI(title="ViewCoin") states = {}
def db(): c = sqlite3.connect(DB_NAME) c.row_factory = sqlite3.Row return c
def now(): return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
def today(): return date.today().isoformat()
def getone(sql, p=()): with db() as c: return c.execute(sql, p).fetchone()
def getall(sql, p=()): with db() as c: return c.execute(sql, p).fetchall()
def execute(sql, p=()): with db() as c: cur = c.execute(sql, p) c.commit() return cur.lastrowid
def get_setting(k, default=""): r = getone("SELECT value FROM settings WHERE key=?", (k,)) return r["value"] if r else default
def set_setting(k, v): execute("""INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value""", (k, str(v)))
def is_admin(uid): return uid == ADMIN_ID or bool(getone( "SELECT 1 FROM admins WHERE user_id=? AND active=1", (uid,) ))
def has_settings_access(uid): if uid == ADMIN_ID: return True r = getone( "SELECT settings_access FROM admins WHERE user_id=? AND active=1", (uid,) ) return bool(r and r["settings_access"])
def init_db(): with db() as c: c.executescript(""" CREATE TABLE IF NOT EXISTS users( user_id INTEGER PRIMARY KEY, username TEXT, full_name TEXT, joined_at TEXT, view_coins INTEGER DEFAULT 0, diamonds INTEGER DEFAULT 0, gift_coins INTEGER DEFAULT 0, total_views INTEGER DEFAULT 0, today_views INTEGER DEFAULT 0, today_views_date TEXT, prizes INTEGER DEFAULT 0, referrals INTEGER DEFAULT 0, referral_earnings INTEGER DEFAULT 0, referral_percent_earnings INTEGER DEFAULT 0, last_daily TEXT ); CREATE TABLE IF NOT EXISTS admins( user_id INTEGER PRIMARY KEY, title TEXT, settings_access INTEGER DEFAULT 0, active INTEGER DEFAULT 1 ); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS mandatory_channels( id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT, link TEXT NOT NULL ); CREATE TABLE IF NOT EXISTS order_options( id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, amount INTEGER NOT NULL, cost INTEGER NOT NULL, active INTEGER DEFAULT 1 ); CREATE TABLE IF NOT EXISTS orders( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, kind TEXT NOT NULL, amount INTEGER NOT NULL, cost INTEGER NOT NULL, target TEXT, source_chat_id INTEGER, source_message_id INTEGER, channel TEXT, channel_message_id INTEGER, created_at TEXT, completed INTEGER DEFAULT 0 ); CREATE TABLE IF NOT EXISTS claims( order_id INTEGER NOT NULL, user_id INTEGER NOT NULL, claimed_at TEXT, PRIMARY KEY(order_id,user_id) ); CREATE TABLE IF NOT EXISTS payments( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, kind TEXT NOT NULL, package_amount INTEGER NOT NULL, price INTEGER NOT NULL, method TEXT, status TEXT DEFAULT 'pending', receipt_file_id TEXT, created_at TEXT, approved_at TEXT ); CREATE TABLE IF NOT EXISTS lottery_rounds( id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, draw_at TEXT, status TEXT DEFAULT 'open' ); CREATE TABLE IF NOT EXISTS lottery_tickets( id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_id INTEGER NOT NULL, user_id INTEGER NOT NULL, payment_id INTEGER, ticket_no INTEGER NOT NULL, created_at TEXT ); CREATE TABLE IF NOT EXISTS lottery_prizes( lottery_id INTEGER NOT NULL, place INTEGER NOT NULL, coins INTEGER DEFAULT 0, diamonds INTEGER DEFAULT 0, PRIMARY KEY(lottery_id,place) ); """)
defaults = {
        "bot_enabled":"1", "view_enabled":"1", "member_enabled":"1",
        "daily_enabled":"1", "daily_coins":"10", "view_reward":"5",
        "member_reward":"5", "referral_coins":"200",
        "welcome_view_bonus":"40", "welcome_member_bonus":"40",
        "monthly_gift_enabled":"1", "monthly_gift_amount":"0",
        "monthly_gift_type":"coins", "lottery_enabled":"1",
        "lottery_date":"", "card_number":"1456799965776",
        "gateway_link":"", "merchant_id":"", "gateway_enabled":"0",
        "coin_packages":"50000:20000,100000:40000,150000:50000,200000:200000",
        "diamond_packages":"100:25000,250:50000,500:100000,1000:200000,4000:800000"
    }
    for k,v in defaults.items():
        c.execute("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)",(k,v))

    if c.execute("SELECT COUNT(*) FROM order_options WHERE kind='view'").fetchone()[0] == 0:
        c.executemany(
            "INSERT INTO order_options(kind,amount,cost) VALUES('view',?,?)",
            [(40,40),(50,50),(100,100),(200,200)]
        )
    if c.execute("SELECT COUNT(*) FROM order_options WHERE kind='member'").fetchone()[0] == 0:
        c.executemany(
            "INSERT INTO order_options(kind,amount,cost) VALUES('member',?,?)",
            [(10,20),(20,40),(30,60),(40,80),(50,100)]
        )
    c.execute(
        """INSERT OR IGNORE INTO admins(user_id,title,settings_access,active)
           VALUES(?,?,1,1)""",(ADMIN_ID,"مدیر اصلی")
    )
    c.commit()
def back(): return InlineKeyboardButton(text="🏠 بازگشت به منوی اصلی", callback_data="home")
def main_menu(uid): rows = [ [("▪︎ جمع‌آوری سکه رایگان","daily")], [("▪︎ حساب کاربری","account"),("▪︎ جذب زیرمجموعه","ref")], [("▪︎ ثبت تبلیغ ویوگیر و ممبرگیر","orders")], [("▪︎ فروشگاه","shop")], [("▪︎ انتقال سکه","transfer_coin"),("▪︎ انتقال الماس","transfer_diamond")], [("▪︎ قرعه‌کشی","lottery")] ] if is_admin(uid): rows.append([("▪︎ پنل مدیریت","admin")]) b=InlineKeyboardBuilder() for r in rows: b.row(*(InlineKeyboardButton(text=t,callback_data=d) for t,d in r)) return b.as_markup()
def back_kb(): return InlineKeyboardMarkup(inline_keyboard=[[back()]])
def account_text(uid): u=getone("SELECT * FROM users WHERE user_id=?",(uid,)) if not u: return "حساب کاربری پیدا نشد." tv=u["today_views"] if u["today_views_date"]==today() else 0 un="@"+u["username"] if u["username"] else "ندارد" return ( "👤 حساب کاربری\n\n" f"نام: {u['full_name'] or 'ندارد'}\n" f"نام کاربری: {un}\nID: {uid}\n\n" f"🎁 هدیه مدیریت: {u['gift_coins']}\n" f"👁 بازدیدهای شما: {u['total_views']}\n" f"📅 بازدیدهای امروز: {tv}\n" f"🏆 جوایز: {u['prizes']}\n" f"👥 تعداد زیرمجموعه‌ها: {u['referrals']}\n" f"💰 دریافتی زیرمجموعه: {u['referral_earnings']}\n" f"📈 پورسانت زیرمجموعه: {u['referral_percent_earnings']}\n" f"🪙 موجودی سکه شما: {u['view_coins']}\n" f"💎 موجودی الماس شما: {u['diamonds']}" )
def options(kind): rows=getall( "SELECT * FROM order_options WHERE kind=? AND active=1 ORDER BY amount",(kind,) ) b=InlineKeyboardBuilder() for o in rows: txt=(f"🪙 {o['cost']} سکه → {o['amount']} ویو" if kind=="view" else f"💎 {o['cost']} الماس → {o['amount']} ممبر") b.row(InlineKeyboardButton(text=txt,callback_data=f"pick_{kind}_{o['id']}")) b.row(back()) return b.as_markup()
def shop_kb(): return InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🪙 خرید سکه ویوگیر",callback_data="shop_coins")], [InlineKeyboardButton(text="💎 خرید الماس ممبرگیر",callback_data="shop_diamonds")], [back()] ])
def parse_packages(key): out=[] for x in get_setting(key,"").split(","): try: a,p=x.split(":"); out.append((int(a),int(p))) except: pass return out
def package_kb(kind): key="coin_packages" if kind=="coins" else "diamond_packages" b=InlineKeyboardBuilder() for a,p in parse_packages(key): unit="🪙 سکه" if kind=="coins" else "💎 الماس" b.row(InlineKeyboardButton( text=f"{a:,} {unit} — {p:,} تومان", callback_data=f"pkg_{kind}{a}{p}" )) b.row(InlineKeyboardButton(text="↩️ بازگشت به فروشگاه",callback_data="shop")) b.row(back()) return b.as_markup()
def payment_kb(pid): return InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="💳 کارت‌به‌کارت و ارسال رسید",callback_data=f"manual_{pid}")], [InlineKeyboardButton(text="🌐 پرداخت از درگاه",callback_data=f"gateway_{pid}")], [back()] ])
async def add_user(m, ref=None): uid=m.from_user.id u=getone("SELECT user_id FROM users WHERE user_id=?",(uid,)) if u: execute("UPDATE users SET username=?,full_name=? WHERE user_id=?", (m.from_user.username,m.from_user.full_name,uid)) return execute("""INSERT INTO users(user_id,username,full_name,joined_at,view_coins, diamonds,today_views_date) VALUES(?,?,?,?,?,?,?)""", (uid,m.from_user.username,m.from_user.full_name,now(), int(get_setting("welcome_view_bonus","40")), int(get_setting("welcome_member_bonus","40")),today())) if ref and ref!=uid and getone("SELECT user_id FROM users WHERE user_id=?",(ref,)): r=int(get_setting("referral_coins","200")) execute("""UPDATE users SET referrals=referrals+1,view_coins=view_coins+?, referral_earnings=referral_earnings+? WHERE user_id=?""",(r,r,ref))
async def membership_ok(uid): for r in getall("SELECT * FROM mandatory_channels"): try: x=await bot.get_chat_member(r["username"],uid) if x.status in ("left","kicked"): return False except: return False return True
@dp.message(CommandStart()) async def start(m:Message): p=(m.text or "").split(maxsplit=1) ref=int(p[1]) if len(p)>1 and p[1].isdigit() else None await add_user(m,ref) await home(m)
async def home(m): if not is_admin(m.from_user.id) and get_setting("bot_enabled","1")!="1": await m.answer("🤖 ربات موقتاً خاموش است.",reply_markup=back_kb()); return if not is_admin(m.from_user.id) and not await membership_ok(m.from_user.id): rows=[] for r in getall("SELECT * FROM mandatory_channels"): rows.append([InlineKeyboardButton(text="عضویت",url=r["link"])]) rows.append([InlineKeyboardButton(text="🔎 بررسی عضویت",callback_data="check_membership")]) await m.answer("برای استفاده ابتدا عضو کانال‌های اجباری شوید.", reply_markup=InlineKeyboardMarkup(inline_keyboard=rows)); return await m.answer( "🚀 به ViewCoin خوش آمدید\n\n" "🪙 سکه ویوگیر و 💎 الماس ممبرگیر جدا هستند.", reply_markup=main_menu(m.from_user.id) )
@dp.message(F.photo) async def photo(m:Message): s=states.get(m.from_user.id,{}) if s.get("action")!="receipt": await m.answer("از منوی ربات استفاده کنید.",reply_markup=main_menu(m.from_user.id)); return pid=s["payment_id"] execute("UPDATE payments SET receipt_file_id=?,method='card' WHERE id=?", (m.photo[-1].file_id,pid)) states.pop(m.from_user.id,None) p=getone("SELECT * FROM payments WHERE id=?",(pid,)) kb=InlineKeyboardMarkup(inline_keyboard=[[ InlineKeyboardButton(text="✅ تأیید",callback_data=f"payok_{pid}"), InlineKeyboardButton(text="❌ رد",callback_data=f"payno_{pid}") ]]) await m.answer("✅ رسید دریافت شد و برای مدیر ارسال شد.") try: await bot.send_photo(ADMIN_ID,m.photo[-1].file_id, caption=f"💳 رسید پرداخت\nID: {p['user_id']}\n" f"مبلغ: {p['price']:,} تومان\nبسته: {p['package_amount']:,}\nنوع: {p['kind']}", reply_markup=kb) except Exception: pass
@dp.message() async def text(m:Message): await add_user(m) uid=m.from_user.id s=states.get(uid,{}) a=s.get("action")
if a=="view_post":
    s.update(action="view_confirm",source_chat_id=m.chat.id,source_message_id=m.message_id)
    await m.answer("پست دریافت شد.\\n\\nبرای ثبت نهایی تأیید کنید.",
                    reply_markup=InlineKeyboardMarkup(inline_keyboard=[
                        [InlineKeyboardButton(text="✅ ثبت پست",callback_data="confirm_view")],
                        [InlineKeyboardButton(text="❌ لغو",callback_data="home")],
                        [back()]
                    ])); return

if a=="member_link":
    target=(m.text or "").strip()
    s.update(action="member_confirm",target=target)
    await m.answer(f"🔗 لینک:\\n{target}\\n\\nثبت نهایی؟",
                    reply_markup=InlineKeyboardMarkup(inline_keyboard=[
                        [InlineKeyboardButton(text="✅ ثبت لینک",callback_data="confirm_member")],
                        [InlineKeyboardButton(text="❌ لغو",callback_data="home")],
                        [back()]
                    ])); return

if a in ("transfer_coin_amount","transfer_diamond_amount"):
    try: amount=int((m.text or "").replace(",",""))
    except: amount=0
    if amount<=0:
        await m.answer("عدد مثبت وارد کنید.",reply_markup=back_kb()); return
    s["amount"]=amount
    s["action"]="transfer_coin_user" if a=="transfer_coin_amount" else "transfer_diamond_user"
    await m.answer("ID عددی گیرنده را وارد کنید.",reply_markup=back_kb()); return

if a in ("transfer_coin_user","transfer_diamond_user"):
    try: target=int((m.text or "").strip())
    except: target=0
    if not getone("SELECT 1 FROM users WHERE user_id=?",(target,)):
        await m.answer("این کاربر در همین ربات ثبت‌نام نکرده است.",reply_markup=back_kb()); return
    amount=s["amount"]; col="view_coins" if a=="transfer_coin_user" else "diamonds"
    u=getone("SELECT * FROM users WHERE user_id=?",(uid,))
    if uid!=ADMIN_ID and u[col]<amount:
        await m.answer("موجودی کافی نیست.",reply_markup=back_kb()); return
    if uid!=ADMIN_ID: execute(f"UPDATE users SET {col}={col}-? WHERE user_id=?",(amount,uid))
    execute(f"UPDATE users SET {col}={col}+? WHERE user_id=?",(amount,target))
    states.pop(uid,None)
    await m.answer("✅ انتقال انجام شد.",reply_markup=back_kb()); return

if a=="admin_text":
    await admin_text(m); return

await m.answer("از دکمه‌های منو استفاده کنید.",reply_markup=main_menu(uid))
async def admin_text(m): uid=m.from_user.id if not has_settings_access(uid): return s=states.get(uid,{}) typ=s.get("type"); val=(m.text or "").strip() if typ=="daily" and val.isdigit(): set_setting("daily_coins",val) elif typ=="ref" and val.isdigit(): set_setting("referral_coins",val) elif typ=="date": set_setting("lottery_date",val) elif typ=="card": set_setting("card_number",val) elif typ=="gateway": set_setting("gateway_link",val) elif typ=="gift": p=val.split() if len(p)==2 and p[0].isdigit(): set_setting("monthly_gift_amount",p[0]) set_setting("monthly_gift_type","diamonds" if p[1] in ("الماس","diamonds") else "coins") else: await m.answer("مثال: 1000 سکه یا 500 الماس"); return else: await m.answer("مقدار نامعتبر است."); return states.pop(uid,None) await m.answer("✅ ذخیره شد.",reply_markup=admin_menu(uid))
---------- USER CALLBACKS ----------
@dp.callback_query(F.data=="home") async def c_home(c:CallbackQuery): await c.answer() states.pop(c.from_user.id,None) await c.message.edit_text("🚀 منوی اصلی",reply_markup=main_menu(c.from_user.id))
@dp.callback_query(F.data=="account") async def c_account(c:CallbackQuery): await c.answer() await c.message.edit_text(account_text(c.from_user.id),reply_markup=back_kb())
@dp.callback_query(F.data=="daily") async def c_daily(c:CallbackQuery): await c.answer() if get_setting("daily_enabled","1")!="1": await c.message.edit_text("جمع‌آوری سکه روزانه خاموش است.",reply_markup=back_kb()); return u=getone("SELECT last_daily FROM users WHERE user_id=?",(c.from_user.id,)) if u and u["last_daily"]==today(): await c.message.edit_text("❌ سکه امروز را گرفته‌اید.",reply_markup=back_kb()); return n=int(get_setting("daily_coins","10")) execute("UPDATE users SET view_coins=view_coins+?,last_daily=? WHERE user_id=?", (n,today(),c.from_user.id)) await c.message.edit_text(f"🎉 {n} سکه دریافت کردید.",reply_markup=back_kb())
@dp.callback_query(F.data=="ref") async def c_ref(c:CallbackQuery): await c.answer() uid=c.from_user.id link=f"https://t.me/{BOT_USERNAME}?start={uid}⁠�" await c.message.edit_text( "👥 جذب زیرمجموعه\n\n" f"🪙 سکه دیدن تبلیغات: {get_setting('view_reward','5')}\n" f"👥 سکه زیرمجموعه‌گیری: {get_setting('referral_coins','200')}\n" f"🪙 سکه روزانه: {get_setting('daily_coins','10')}\n" f"💎 پاداش ممبرگیر: {get_setting('member_reward','5')}\n\n" f"🔗 لینک دعوت:\n{link}",reply_markup=back_kb())
@dp.callback_query(F.data=="orders") async def c_orders(c:CallbackQuery): await c.answer() await c.message.edit_text("نوع تبلیغ را انتخاب کنید:",reply_markup=InlineKeyboardMarkup( inline_keyboard=[ [InlineKeyboardButton(text="ثبت تبلیغ ویوگیر",callback_data="new_view")], [InlineKeyboardButton(text="ثبت تبلیغ ممبرگیر",callback_data="new_member")], [back()] ]))
@dp.callback_query(F.data=="new_view") async def c_new_view(c:CallbackQuery): await c.answer() await c.message.edit_text("تعداد ویو را انتخاب کنید:",reply_markup=options("view"))
@dp.callback_query(F.data=="new_member") async def c_new_member(c:CallbackQuery): await c.answer() await c.message.edit_text("تعداد ممبر را انتخاب کنید:",reply_markup=options("member"))
@dp.callback_query(F.data.startswith("pick_view_")) async def c_pick_view(c:CallbackQuery): await c.answer() oid=int(c.data.rsplit("_",1)[1]) o=getone("SELECT * FROM order_options WHERE id=? AND kind='view' AND active=1",(oid,)) if not o: return states[c.from_user.id]={"action":"view_post","order_id":oid} await c.message.edit_text( f"انتخاب شد: {o['cost']} سکه → {o['amount']} ویو\n\nپست مورد نظر را همینجا ارسال کنید.", reply_markup=InlineKeyboardMarkup(inline_keyboard=[[back()]]) )
@dp.callback_query(F.data=="confirm_view") async def c_confirm_view(c:CallbackQuery): await c.answer() uid=c.from_user.id; s=states.get(uid,{}) o=getone("SELECT * FROM order_options WHERE id=?",(s.get("order_id"),)) u=getone("SELECT view_coins FROM users WHERE user_id=?",(uid,)) if not o or not u or u["view_coins"]<o["cost"]: states.pop(uid,None); await c.message.edit_text("❌ موجودی سکه کافی نیست.",reply_markup=back_kb()); return try: sent=await bot.copy_message( VIEW_CHANNEL,s["source_chat_id"],s["source_message_id"], reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🔎 ثبت بازدید",callback_data="pending")], [InlineKeyboardButton(text="🤖 ورود به ربات",url=f"https://t.me/{BOT_USERNAME}⁠�")] ])) except Exception: await c.message.edit_text("❌ ربات نتوانست پست را به کانال ویوگیر بفرستد. دسترسی ارسال پیام را بررسی کنید.",reply_markup=back_kb()) return oid=execute("""INSERT INTO orders(user_id,kind,amount,cost,source_chat_id,source_message_id, channel,channel_message_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)""", (uid,"view",o["amount"],o["cost"],s["source_chat_id"],s["source_message_id"], VIEW_CHANNEL,sent.message_id,now())) execute("UPDATE users SET view_coins=view_coins-? WHERE user_id=?",(o["cost"],uid)) try: await bot.edit_message_reply_markup( VIEW_CHANNEL,sent.message_id, reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🔎 ثبت بازدید",callback_data=f"claim_view_{oid}")], [InlineKeyboardButton(text="🤖 ورود به ربات",url=f"https://t.me/{BOT_USERNAME}⁠�")] ])) except: pass states.pop(uid,None) await c.message.edit_text(f"✅ سفارش ویو #{oid} ثبت شد.",reply_markup=back_kb())
@dp.callback_query(F.data.startswith("claim_view_")) async def c_claim_view(c:CallbackQuery): oid=int(c.data.rsplit("_",1)[1]); o=getone("SELECT * FROM orders WHERE id=?",(oid,)) if not o or o["completed"]: await c.answer("این سفارش تمام شده است.",show_alert=True); return uid=c.from_user.id if getone("SELECT 1 FROM claims WHERE order_id=? AND user_id=?",(oid,uid)): await c.answer("قبلاً برای این سفارش سکه گرفته‌اید.",show_alert=True); return execute("INSERT INTO claims(order_id,user_id,claimed_at) VALUES(?,?,?)",(oid,uid,now())) reward=int(get_setting("view_reward","5")) u=getone("SELECT today_views_date FROM users WHERE user_id=?",(uid,)) execute("""UPDATE users SET view_coins=view_coins+?,total_views=total_views+1, today_views=CASE WHEN today_views_date=? THEN today_views+1 ELSE 1 END, today_views_date=? WHERE user_id=?""",(reward,today(),today(),uid)) n=getone("SELECT COUNT(*) n FROM claims WHERE order_id=?",(oid,))["n"] if n>=o["amount"]: execute("UPDATE orders SET completed=1 WHERE id=?",(oid,)) try: await bot.delete_message(o["channel"],o["channel_message_id"]) except: pass await c.answer(f"🪙 {reward} سکه دریافت شد.",show_alert=True)
@dp.callback_query(F.data.startswith("pick_member_")) async def c_pick_member(c:CallbackQuery): await c.answer() oid=int(c.data.rsplit("_",1)[1]) o=getone("SELECT * FROM order_options WHERE id=? AND kind='member' AND active=1",(oid,)) if not o:return states[c.from_user.id]={"action":"member_link","order_id":oid} await c.message.edit_text( f"انتخاب شد: {o['cost']} الماس → {o['amount']} ممبر\n\nلینک کانال یا گروه را ارسال کنید.", reply_markup=back_kb())
def normalize(t): t=t.strip() if t.startswith(("https://t.me/⁠�","http://t.me/⁠�")): x=t.rstrip("/").split("/")[-1].split("?")[0] if x and not x.startswith(("+","joinchat")): return "@"+x return t
@dp.callback_query(F.data=="confirm_member") async def c_confirm_member(c:CallbackQuery): await c.answer() uid=c.from_user.id; s=states.get(uid,{}) o=getone("SELECT * FROM order_options WHERE id=?",(s.get("order_id"),)) u=getone("SELECT diamonds FROM users WHERE user_id=?",(uid,)) if not o or not u or u["diamonds"]<o["cost"]: states.pop(uid,None); await c.message.edit_text("❌ الماس کافی نیست.",reply_markup=back_kb()); return target=s["target"] try: sent=await bot.send_message( MEMBER_CHANNEL,"👥 سفارش ممبر\n\nبرای عضویت روی جوین بزنید.", reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🔗 جوین",url=target)], [InlineKeyboardButton(text="💎 دریافت الماس",callback_data="pending")], [InlineKeyboardButton(text="🤖 ورود به ربات",url=f"https://t.me/{BOT_USERNAME}⁠�")] ])) except: await c.message.edit_text("❌ ارسال سفارش به کانال ممبرگیر انجام نشد.",reply_markup=back_kb()); return oid=execute("""INSERT INTO orders(user_id,kind,amount,cost,target,channel, channel_message_id,created_at) VALUES(?,?,?,?,?,?,?,?)""", (uid,"member",o["amount"],o["cost"],target,MEMBER_CHANNEL,sent.message_id,now())) execute("UPDATE users SET diamonds=diamonds-? WHERE user_id=?",(o["cost"],uid)) try: await bot.edit_message_reply_markup( MEMBER_CHANNEL,sent.message_id, reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🔗 جوین",url=target)], [InlineKeyboardButton(text="💎 دریافت الماس",callback_data=f"claim_member_{oid}")], [InlineKeyboardButton(text="🤖 ورود به ربات",url=f"https://t.me/{BOT_USERNAME}⁠�")] ])) except: pass states.pop(uid,None) await c.message.edit_text(f"✅ سفارش ممبر #{oid} ثبت شد.",reply_markup=back_kb())
@dp.callback_query(F.data.startswith("claim_member_")) async def c_claim_member(c:CallbackQuery): oid=int(c.data.rsplit("_",1)[1]); o=getone("SELECT * FROM orders WHERE id=?",(oid,)) if not o or o["completed"]: await c.answer("این سفارش تمام شده است.",show_alert=True); return uid=c.from_user.id if getone("SELECT 1 FROM claims WHERE order_id=? AND user_id=?",(oid,uid)): await c.answer("قبلاً الماس گرفته‌اید.",show_alert=True); return try: x=await bot.get_chat_member(normalize(o["target"]),uid) if x.status in ("left","kicked"): raise RuntimeError() except: await c.answer("❌ ابتدا عضو شوید و دوباره بزنید.",show_alert=True); return execute("INSERT INTO claims(order_id,user_id,claimed_at) VALUES(?,?,?)",(oid,uid,now())) reward=int(get_setting("member_reward","5")) execute("UPDATE users SET diamonds=diamonds+? WHERE user_id=?",(reward,uid)) n=getone("SELECT COUNT(*) n FROM claims WHERE order_id=?",(oid,))["n"] if n>=o["amount"]: execute("UPDATE orders SET completed=1 WHERE id=?",(oid,)) try: await bot.delete_message(o["channel"],o["channel_message_id"]) except: pass await c.answer(f"💎 {reward} الماس دریافت شد.",show_alert=True)
@dp.callback_query(F.data=="shop") async def c_shop(c:CallbackQuery): await c.answer(); await c.message.edit_text("🏪 فروشگاه",reply_markup=shop_kb())
@dp.callback_query(F.data.in_({"shop_coins","shop_diamonds"})) async def c_shop_kind(c:CallbackQuery): await c.answer() k="coins" if c.data=="shop_coins" else "diamonds" await c.message.edit_text( "🪙 خرید سکه ویوگیر" if k=="coins" else "💎 خرید الماس ممبرگیر", reply_markup=package_kb(k))
@dp.callback_query(F.data.startswith("pkg_")) async def c_package(c:CallbackQuery): await c.answer() ,kind,amount,price=c.data.split("") pid=execute("""INSERT INTO payments(user_id,kind,package_amount,price,method,created_at) VALUES(?,?,?,?,?,?)""", (c.from_user.id,kind,int(amount),int(price),"pending",now())) await c.message.edit_text( f"🧾 بسته: {int(amount):,}\n💰 مبلغ: {int(price):,} تومان\n\nروش پرداخت را انتخاب کنید:", reply_markup=payment_kb(pid))
@dp.callback_query(F.data.startswith("manual_")) async def c_manual(c:CallbackQuery): await c.answer() pid=int(c.data.rsplit("_",1)[1]); p=getone("SELECT * FROM payments WHERE id=?",(pid,)) states[c.from_user.id]={"action":"receipt","payment_id":pid} execute("UPDATE payments SET method='card' WHERE id=?",(pid,)) await c.message.edit_text( f"💳 کارت‌به‌کارت\n\n" f"شماره کارت: {get_setting('card_number')}\n" f"مبلغ: {p['price']:,} تومان\n\n" "بعد از واریز عکس تراکنش را همینجا بفرستید.", reply_markup=back_kb())
@dp.callback_query(F.data.startswith("gateway_")) async def c_gateway(c:CallbackQuery): await c.answer() pid=int(c.data.rsplit("_",1)[1]); p=getone("SELECT * FROM payments WHERE id=?",(pid,)) link=get_setting("gateway_link","") if not link: await c.message.edit_text("⚠️ لینک درگاه توسط مدیر تنظیم نشده.",reply_markup=back_kb()); return execute("UPDATE payments SET method='gateway' WHERE id=?",(pid,)) sep="&" if "?" in link else "?" url=f"{link}{sep}payment_id={pid}&user_id={c.from_user.id}&amount={p['price']}" await c.message.edit_text("🌐 برای پرداخت وارد درگاه شوید.", reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="💳 ورود به درگاه",url=url)], [back()] ]))
def ticket_count(price): return {50000:2,100000:4,200000:6,500000:10}.get(int(price),0)
def add_tickets(uid,pid,n): r=getone("SELECT id FROM lottery_rounds WHERE status='open' ORDER BY id DESC LIMIT 1") if not r:return mx=getone("SELECT COALESCE(MAX(ticket_no),0) n FROM lottery_tickets WHERE lottery_id=?",(r["id"],))["n"] with db() as c: for _ in range(n): mx+=1 c.execute("""INSERT INTO lottery_tickets(lottery_id,user_id,payment_id,ticket_no,created_at) VALUES(?,?,?,?,?)""",(r["id"],uid,pid,mx,now())) c.commit()
@dp.callback_query(F.data.startswith("payok_")) async def c_payok(c:CallbackQuery): if not is_admin(c.from_user.id): await c.answer("دسترسی ندارید.",show_alert=True); return pid=int(c.data.rsplit("_",1)[1]); p=getone("SELECT * FROM payments WHERE id=?",(pid,)) if not p or p["status"]!="pending": await c.answer("قبلاً بررسی شده.",show_alert=True); return execute("UPDATE payments SET status='approved',approved_at=? WHERE id=?",(now(),pid)) n=ticket_count(p["price"]) if get_setting("lottery_enabled","1")=="1" else 0 if n:add_tickets(p["user_id"],pid,n) try: await c.message.edit_reply_markup(reply_markup=None) await bot.send_message(p["user_id"], f"✅ پرداخت {p['price']:,} تومان تأیید شد.\n🎟️ {n} بلیت قرعه‌کشی اضافه شد.\n" "در خرید کارت‌به‌کارت، سکه/الماس را مدیر به‌صورت دستی انتقال می‌دهد.") except: pass await c.answer("تأیید شد.")
@dp.callback_query(F.data.startswith("payno_")) async def c_payno(c:CallbackQuery): if not is_admin(c.from_user.id): await c.answer("دسترسی ندارید.",show_alert=True); return pid=int(c.data.rsplit("_",1)[1]); p=getone("SELECT * FROM payments WHERE id=?",(pid,)) if p: execute("UPDATE payments SET status='rejected' WHERE id=?",(pid,)) try: await bot.send_message(p["user_id"],"❌ رسید پرداخت رد شد.") except: pass await c.message.edit_reply_markup(reply_markup=None); await c.answer("رد شد.")
@dp.callback_query(F.data=="lottery") async def c_lottery(c:CallbackQuery): await c.answer() if get_setting("lottery_enabled","1")!="1": await c.message.edit_text("🎟️ قرعه‌کشی خاموش است.",reply_markup=back_kb()); return r=getone("SELECT * FROM lottery_rounds WHERE status='open' ORDER BY id DESC LIMIT 1") n=getone("SELECT COUNT(*) n FROM lottery_tickets WHERE lottery_id=? AND user_id=?", (r["id"],c.from_user.id))["n"] if r else 0 await c.message.edit_text( "🎟️ به قرعه‌کشی ربات خوش آمدید\n\n" "برای ورود باید از ربات خرید کنید و بلیت شانس دریافت کنید.\n\n" "۵۰,۰۰۰ تومان → ۲ بلیت\n" "۱۰۰,۰۰۰ تومان → ۴ بلیت\n" "۲۰۰,۰۰۰ تومان → ۶ بلیت\n" "۵۰۰,۰۰۰ تومان → ۱۰ بلیت\n\n" f"🎟️ بلیت‌های دور فعلی شما: {n}", reply_markup=InlineKeyboardMarkup(inline_keyboard=[ [InlineKeyboardButton(text="🪙 خرید سکه",callback_data="shop_coins")], [InlineKeyboardButton(text="💎 خرید الماس",callback_data="shop_diamonds")], [back()] ]))
@dp.callback_query(F.data=="transfer_coin") async def c_tc(c:CallbackQuery): await c.answer(); states[c.from_user.id]={"action":"transfer_coin_amount"} await c.message.edit_text("🪙 تعداد سکه را وارد کنید.",reply_markup=back_kb())
@dp.callback_query(F.data=="transfer_diamond") async def c_td(c:CallbackQuery): await c.answer(); states[c.from_user.id]={"action":"transfer_diamond_amount"} await c.message.edit_text("💎 تعداد الماس را وارد کنید.",reply_markup=back_kb())
---------- ADMIN ----------
def admin_menu(uid): rows=[ [("⚙️ تنظیم سفارشات ویو","aset_view"),("⚙️ تنظیم سفارش ممبر","aset_member")], [("🛒 تنظیم فروشگاه خرید","aset_shop"),("🪙 تنظیم سکه روزانه","aset_daily")], [("👥 تنظیم سکه زیرمجموعه","aset_ref"),("🎁 تنظیم هدیه مدیریت","aset_gift")], [("🎟️ تنظیم قرعه‌کشی","aset_lottery"),("📅 تنظیم تاریخ قرعه‌کشی","aset_date")], [("🔘 روشن/خاموش قرعه‌کشی","aset_lottery_on"),("🤖 روشن/خاموش ربات","aset_bot_on")], [("👑 دسترسی مدیران","admins"),("🔗 عضویت اجباری","mandatory")], [("📊 آمار","stats"),("💳 پرداخت‌ها","payments")], [("↩️ منوی کاربر","home")] ] b=InlineKeyboardBuilder() for r in rows:b.row(*(InlineKeyboardButton(text=t,callback_data=d) for t,d in r)) return b.as_markup()
@dp.callback_query(F.data=="admin") async def c_admin(c:CallbackQuery): await c.answer() if not is_admin(c.from_user.id):return await c.message.edit_text("👑 پنل مدیریت",reply_markup=admin_menu(c.from_user.id))
@dp.callback_query(F.data=="stats") async def c_stats(c:CallbackQuery): if not is_admin(c.from_user.id):return await c.answer() u=getone("SELECT COUNT() n FROM users")["n"] o=getone("SELECT COUNT() n FROM orders")["n"] co=getone("SELECT COALESCE(SUM(view_coins),0) n FROM users")["n"] di=getone("SELECT COALESCE(SUM(diamonds),0) n FROM users")["n"] await c.message.edit_text(f"📊 آمار\n\n👥 کاربران: {u}\n📢 سفارش‌ها: {o}\n🪙 سکه: {co:,}\n💎 الماس: {di:,}", reply_markup=back_kb())
@dp.callback_query(F.data=="admin_users") async def c_users(c:CallbackQuery): if not is_admin(c.from_user.id):return await c.answer() rows=getall("SELECT user_id,username,view_coins,diamonds FROM users ORDER BY joined_at DESC LIMIT 30") txt="👥 کاربران\n\n" txt+="\n".join(f"{r['user_id']} | @{r['username'] or '-'} | 🪙{r['view_coins']} | 💎{r['diamonds']}" for r in rows) await c.message.edit_text(txt or "کاربری نیست.",reply_markup=back_kb())
@dp.callback_query(F.data=="aset_daily") async def a_daily(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer(); states[c.from_user.id]={"action":"admin_text","type":"daily"} await c.message.edit_text(f"سکه روزانه فعلی: {get_setting('daily_coins','10')}\nمقدار جدید را بفرستید.",reply_markup=back_kb())
@dp.callback_query(F.data=="aset_ref") async def a_ref(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer(); states[c.from_user.id]={"action":"admin_text","type":"ref"} await c.message.edit_text(f"پاداش زیرمجموعه فعلی: {get_setting('referral_coins','200')}\nمقدار جدید را بفرستید.",reply_markup=back_kb())
@dp.callback_query(F.data=="aset_gift") async def a_gift(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer(); states[c.from_user.id]={"action":"admin_text","type":"gift"} await c.message.edit_text("مثال: 1000 سکه یا 500 الماس",reply_markup=back_kb())
@dp.callback_query(F.data=="aset_date") async def a_date(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer(); states[c.from_user.id]={"action":"admin_text","type":"date"} await c.message.edit_text("تاریخ و ساعت را بفرستید. مثال: 2026-12-31 20:00",reply_markup=back_kb())
@dp.callback_query(F.data=="aset_lottery_on") async def a_lot_on(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() v="0" if get_setting("lottery_enabled","1")=="1" else "1"; set_setting("lottery_enabled",v) await c.message.edit_text(f"🎟️ قرعه‌کشی: {'🟢 روشن' if v=='1' else '🔴 خاموش'}",reply_markup=admin_menu(c.from_user.id))
@dp.callback_query(F.data=="aset_bot_on") async def a_bot_on(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() v="0" if get_setting("bot_enabled","1")=="1" else "1"; set_setting("bot_enabled",v) await c.message.edit_text(f"🤖 ربات: {'🟢 روشن' if v=='1' else '🔴 خاموش'}",reply_markup=admin_menu(c.from_user.id))
@dp.callback_query(F.data=="aset_view") async def a_view(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() rows=getall("SELECT * FROM order_options WHERE kind='view' ORDER BY amount") txt="⚙️ تنظیم سفارشات ویو\n\n" txt+="\n".join(f"ID {r['id']}: {r['cost']} سکه → {r['amount']} ویو" for r in rows) txt+="\n\n/setview ID تعداد_ویو هزینه" await c.message.edit_text(txt,reply_markup=back_kb())
@dp.callback_query(F.data=="aset_member") async def a_member(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() rows=getall("SELECT * FROM order_options WHERE kind='member' ORDER BY amount") txt="⚙️ تنظیم سفارش ممبر\n\n" txt+="\n".join(f"ID {r['id']}: {r['cost']} الماس → {r['amount']} ممبر" for r in rows) txt+="\n\n/setmember ID تعداد_ممبر هزینه" await c.message.edit_text(txt,reply_markup=back_kb())
@dp.callback_query(F.data=="aset_shop") async def a_shop(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() await c.message.edit_text( "🛒 تنظیم فروشگاه\n\n" f"🪙 سکه: {get_setting('coin_packages')}\n" f"💎 الماس: {get_setting('diamond_packages')}\n" f"💳 کارت: {get_setting('card_number')}\n" f"🌐 درگاه: {'تنظیم شده' if get_setting('gateway_link') else 'تنظیم نشده'}\n\n" "/setcoinpackages مقدار:قیمت,...\n" "/setdiamondpackages مقدار:قیمت,...\n" "/setcard شماره_کارت\n" "/setgateway لینک_درگاه", reply_markup=back_kb())
@dp.callback_query(F.data=="aset_lottery") async def a_lottery(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() await c.message.edit_text( "🎟️ تنظیم قرعه‌کشی\n\n" "برای دور باز، جایزه را تنظیم کنید:\n" "/prize جایگاه سکه الماس\n" "مثال: /prize 1 10000 500", reply_markup=back_kb())
@dp.callback_query(F.data=="admins") async def a_admins(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() rows=getall("SELECT * FROM admins ORDER BY user_id") txt="👑 مدیران\n\n" txt+="\n".join( f"ID {r['user_id']} | تنظیمات: {'بله' if r['settings_access'] else 'خیر'}" for r in rows) txt+="\n\n/addadmin ID بله\n/addadmin ID خیر" await c.message.edit_text(txt,reply_markup=back_kb())
@dp.callback_query(F.data=="mandatory") async def a_mandatory(c:CallbackQuery): if not has_settings_access(c.from_user.id):return await c.answer() rows=getall("SELECT * FROM mandatory_channels ORDER BY id") txt="🔗 عضویت اجباری\n\n" txt+="\n".join(f"{r['id']}. {r['username'] or r['link']}" for r in rows) txt+="\n\n/addchannel @channel https://t.me/channel\n/delchannel⁠� ID" await c.message.edit_text(txt,reply_markup=back_kb())
@dp.callback_query(F.data=="payments") async def a_payments(c:CallbackQuery): if not is_admin(c.from_user.id):return await c.answer() rows=getall("SELECT * FROM payments ORDER BY id DESC LIMIT 30") txt="💳 پرداخت‌ها\n\n" txt+="\n".join(f"#{r['id']} | ID {r['user_id']} | {r['price']:,} | {r['status']}" for r in rows) await c.message.edit_text(txt or "پرداختی نیست.",reply_markup=back_kb())
@dp.message(Command("addadmin")) async def cmd_addadmin(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)<2 or not p[1].isdigit(): await m.answer("/addadmin ID بله"); return access=1 if len(p)>2 and p[2].lower() in ("بله","yes","1") else 0 execute("""INSERT INTO admins(user_id,title,settings_access,active) VALUES(?,?,?,1) ON CONFLICT(user_id) DO UPDATE SET active=1,settings_access=excluded.settings_access""", (int(p[1]),"مدیر",access)) await m.answer("✅ مدیر ثبت شد.")
@dp.message(Command("setview")) async def cmd_setview(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)!=4 or not all(x.isdigit() for x in p[1:]): await m.answer("/setview ID تعداد_ویو هزینه");return execute("UPDATE order_options SET amount=?,cost=? WHERE id=? AND kind='view'", (int(p[2]),int(p[3]),int(p[1]))) await m.answer("✅ سفارش ویو تغییر کرد.")
@dp.message(Command("setmember")) async def cmd_setmember(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)!=4 or not all(x.isdigit() for x in p[1:]): await m.answer("/setmember ID تعداد_ممبر هزینه");return execute("UPDATE order_options SET amount=?,cost=? WHERE id=? AND kind='member'", (int(p[2]),int(p[3]),int(p[1]))) await m.answer("✅ سفارش ممبر تغییر کرد.")
@dp.message(Command("setcoinpackages")) async def cmd_coins(m:Message): if not has_settings_access(m.from_user.id):return set_setting("coin_packages",(m.text or "").partition(" ")[2].strip()) await m.answer("✅ فروشگاه سکه ذخیره شد.")
@dp.message(Command("setdiamondpackages")) async def cmd_diamonds(m:Message): if not has_settings_access(m.from_user.id):return set_setting("diamond_packages",(m.text or "").partition(" ")[2].strip()) await m.answer("✅ فروشگاه الماس ذخیره شد.")
@dp.message(Command("setcard")) async def cmd_card(m:Message): if not has_settings_access(m.from_user.id):return set_setting("card_number",(m.text or "").partition(" ")[2].strip()) await m.answer("✅ شماره کارت ذخیره شد.")
@dp.message(Command("setgateway")) async def cmd_gateway(m:Message): if not has_settings_access(m.from_user.id):return set_setting("gateway_link",(m.text or "").partition(" ")[2].strip()) await m.answer("✅ لینک درگاه ذخیره شد.")
@dp.message(Command("prize")) async def cmd_prize(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)!=4 or not all(x.isdigit() for x in p[1:]): await m.answer("/prize جایگاه سکه الماس");return r=getone("SELECT id FROM lottery_rounds WHERE status='open' ORDER BY id DESC LIMIT 1") if not r: await m.answer("اول دور قرعه‌کشی بسازید.");return execute("""INSERT INTO lottery_prizes(lottery_id,place,coins,diamonds) VALUES(?,?,?,?) ON CONFLICT(lottery_id,place) DO UPDATE SET coins=excluded.coins,diamonds=excluded.diamonds""", (r["id"],int(p[1]),int(p[2]),int(p[3]))) await m.answer("✅ جایزه ذخیره شد.")
@dp.message(Command("lottery_new")) async def cmd_lottery_new(m:Message): if not has_settings_access(m.from_user.id):return x=(m.text or "").partition(" ")[2].strip() title,sep,draw=x.partition("|") if not sep: await m.answer("/lottery_new عنوان|2026-12-31 20:00");return execute("UPDATE lottery_rounds SET status='closed' WHERE status='open'") lid=execute("INSERT INTO lottery_rounds(title,draw_at,status) VALUES(?,?,'open')",(title,draw)) for place in (1,2,3): execute("INSERT OR IGNORE INTO lottery_prizes(lottery_id,place,coins,diamonds) VALUES(?,?,0,0)", (lid,place)) set_setting("lottery_date",draw) await m.answer("✅ دور جدید ساخته شد.")
@dp.message(Command("addchannel")) async def cmd_addchannel(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)<3: await m.answer("/addchannel @channel https://t.me/channel⁠�");return execute("INSERT INTO mandatory_channels(username,link) VALUES(?,?)",(p[1],p[2])) await m.answer("✅ کانال اضافه شد.")
@dp.message(Command("delchannel")) async def cmd_delchannel(m:Message): if not has_settings_access(m.from_user.id):return p=(m.text or "").split() if len(p)==2 and p[1].isdigit():execute("DELETE FROM mandatory_channels WHERE id=?",(int(p[1]),)) await m.answer("✅ انجام شد.")
@dp.callback_query(F.data=="check_membership") async def c_check(c:CallbackQuery): if await membership_ok(c.from_user.id): await c.answer("✅ عضویت تأیید شد.",show_alert=True) await c.message.edit_text("عضویت تأیید شد.",reply_markup=main_menu(c.from_user.id)) else: await c.answer("❌ هنوز عضو همه کانال‌ها نیستید.",show_alert=True)
@app.get("/") async def root(): return {"status":"ok","service":"ViewCoin"}
@app.get("/payment/callback") async def payment_callback(payment_id:Optional[int]=None,status:Optional[str]=None): # این مسیر فقط اسکلت callback است؛ تأیید واقعی باید طبق API درگاه پیاده‌سازی شود. return {"ok":True,"payment_id":payment_id,"status":status}
@app.post("/telegram/webhook") async def webhook(update:dict): from aiogram.types import Update await dp.feed_update(bot,Update.model_validate(update)) return {"ok":True}
@app.on_event("startup") async def startup(): init_db() if WEBHOOK_URL: await bot.set_webhook(f"{WEBHOOK_URL}/telegram/webhook") else: await bot.delete_webhook(drop_pending_updates=True)
@app.on_event("shutdown") async def shutdown(): await bot.session.close()
if name=="main": import uvicorn init_db() uvicorn.run(app,host="0.0.0.0",port=PORT) '''
req = """aiogram>=3.7,<4 fastapi>=0.110 uvicorn[standard]>=0.29 """
out = Path("/mnt/data/ViewCoin_main.py") out.write_text(main_py, encoding="utf-8") Path("/mnt/data/requirements.txt").write_text(req, encoding="utf-8") print("ساخته شد:", out) print("main.py lines:", len(main_py.splitlines())) print("requirements.txt آماده است.")
